In [1]:
import torch

In [2]:
t1 = torch.tensor(4.)
t1

tensor(4.)

In [3]:
t1.dtype

torch.float32

In [4]:
#vector
t2 = torch.tensor([1., 2, 3, 4])
t2

tensor([1., 2., 3., 4.])

In [5]:
# matrix
t3 = torch.tensor([[5., 6], 
                   [7, 8], 
                   [9, 10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [6]:
# 3-dimensional array
t4 = torch.tensor([
    [[11, 12, 13], 
     [13, 14, 15]], 
    [[15, 16, 17], 
     [17, 18, 19.]]])
t4

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])

In [7]:
print(t1)
t1.shape

tensor(4.)


torch.Size([])

In [8]:
print(t2)
t2.shape

tensor([1., 2., 3., 4.])


torch.Size([4])

In [9]:
print(t3)
t3.shape

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])


torch.Size([3, 2])

In [10]:
print(t4)
t4.shape

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])


torch.Size([2, 2, 3])

# Tensor operations and gradients

In [11]:
# creating tensors
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad = True)
b = torch.tensor(5., requires_grad = True)
x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [12]:
# arithmetic operations
y = w*x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [13]:
# computing derivative
y.backward()

# the derivatives wrt to each variable is stores in the .grad attribute of respective variable

In [14]:
# displaying the gradients
print('dy/dx :', x.grad)
print('dy/dw:', w.grad)
print('dy/db :', b.grad)

# we can see that the dy/dx does not have a derivative value, this is because we didn't
# set the requires_grad = True
# this is done to reduce computation time and resources, if derivative not needed

dy/dx : None
dy/dw: tensor(3.)
dy/db : tensor(1.)


# Tensor functions

In [15]:
t6 = torch.full((3,2), 42.)
t6

tensor([[42., 42.],
        [42., 42.],
        [42., 42.]])

In [16]:
t7 = torch.cat((t3,t6))
t7

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [42., 42.],
        [42., 42.],
        [42., 42.]])

In [17]:
t8 = torch.sin(t7)
t8

tensor([[-0.9589, -0.2794],
        [ 0.6570,  0.9894],
        [ 0.4121, -0.5440],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165]])

In [18]:
t9 = t8.reshape(3,2,2)
t9

tensor([[[-0.9589, -0.2794],
         [ 0.6570,  0.9894]],

        [[ 0.4121, -0.5440],
         [-0.9165, -0.9165]],

        [[-0.9165, -0.9165],
         [-0.9165, -0.9165]]])

# Interoperablility with numpy

In [19]:
import numpy as np

In [20]:
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [21]:
# convert numpy array to torch tensor
y = torch.from_numpy(x)
y

tensor([[1, 2],
        [3, 4]])

In [22]:
x.dtype, y.dtype

(dtype('int64'), torch.int64)

In [23]:
# convert torch tensor to numpy
z = y.numpy()
z

array([[1, 2],
       [3, 4]])

In [24]:
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')


In [25]:
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [26]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


# Linear regression model from scratch


In [27]:
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[-1.7261,  0.6627,  1.8791],
        [ 1.1102,  1.4256,  0.2952]], requires_grad=True)
tensor([ 0.2373, -0.3218], requires_grad=True)


In [28]:
def model(x):
    return x@w.t()+b
# @ is matrix multiplication

In [29]:
# generate predictions
preds = model(inputs)
print(preds)

tensor([[ -0.5668, 188.9372],
        [ 21.7406, 245.0595],
        [ 47.8563, 304.4265],
        [-77.8041, 185.1471],
        [ 76.2914, 233.8111]], grad_fn=<AddBackward0>)


In [30]:
# compare with targets
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [31]:
# implementation of mse
diff = preds - targets
torch.sum(diff*diff)/diff.numel()
# numel gives the total number of inputs

tensor(12186.2520, grad_fn=<DivBackward0>)

# Loss function

In [32]:
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

In [33]:
loss = mse(preds, targets)
print(loss)

tensor(12186.2520, grad_fn=<DivBackward0>)


# Computing gradients

In [34]:
loss.backward()

In [35]:
# gradient for weights
print(w)
print(w.grad)

tensor([[-1.7261,  0.6627,  1.8791],
        [ 1.1102,  1.4256,  0.2952]], requires_grad=True)
tensor([[-5546.8794, -5078.7314, -3182.7324],
        [11947.7812, 12201.8740,  7559.0127]])


In [36]:
print(b)
print(b.grad)

tensor([ 0.2373, -0.3218], requires_grad=True)
tensor([-62.6965, 139.4763])


# Adjusting weights and biases to reduce the loss

In [37]:
# torch.no_grad() indicates to pytorch not to track, modify gradients when updating other
# variable, in this case weights and biases
with torch.no_grad():
    alpha= 1e-5 # learning rate
    w -= w.grad * alpha
    b -= b.grad * alpha

In [38]:
print(w)
print(b)

tensor([[-1.6706,  0.7135,  1.9109],
        [ 0.9907,  1.3036,  0.2196]], requires_grad=True)
tensor([ 0.2380, -0.3232], requires_grad=True)


In [39]:
loss = mse(model(inputs), targets)
print(loss)

tensor(8402.9092, grad_fn=<DivBackward0>)


In [40]:
# we need to set the gradients to zero otherwise recomputation of gradients adds to the
# existing gradient 
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


# Train the model using gradient descent


In [41]:
# Generate predictions
preds = model(inputs)
print(preds)

tensor([[  8.2543, 168.7883],
        [ 33.2952, 218.6102],
        [ 61.3342, 273.2958],
        [-68.7842, 164.9153],
        [ 87.2229, 208.5606]], grad_fn=<AddBackward0>)


In [42]:
# Calculate the loss
loss = mse(preds, targets)
print(loss)

tensor(8402.9092, grad_fn=<DivBackward0>)


In [43]:
# Compute gradients
loss.backward()
print(w.grad)
print(b.grad)

tensor([[-4638.4229, -4108.5059, -2582.8413],
        [ 9869.3721,  9973.2666,  6182.8438]])
tensor([-51.9355, 114.8341])


In [44]:
# Adjust weights & reset gradients
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [45]:
print(w)
print(b)

tensor([[-1.6243,  0.7546,  1.9367],
        [ 0.8921,  1.2039,  0.1578]], requires_grad=True)
tensor([ 0.2385, -0.3243], requires_grad=True)


In [46]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(5851.4922, grad_fn=<DivBackward0>)


# Train for multiple epochs

In [47]:
# Train for 100 epochs
for i in range(100):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [48]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(249.6223, grad_fn=<DivBackward0>)


In [49]:
# Predictions
preds

tensor([[ 52.1549,  73.9327],
        [ 88.0198,  96.1411],
        [113.5281, 137.4325],
        [ -7.3470,  57.6950],
        [128.6705,  99.1255]], grad_fn=<AddBackward0>)

In [50]:
# Targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

# Why not use numpy?
- using pytorch we can easily compute the gradients
- pytorch supports gpu, whereas numpy doesn't

# Linear regression using PyTorch built-ins

In [51]:
import torch.nn as nn

In [52]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [53]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 74.,  66.,  43.],
        [ 91.,  87.,  65.],
        [ 88., 134.,  59.],
        [101.,  44.,  37.],
        [ 68.,  96.,  71.],
        [ 73.,  66.,  44.],
        [ 92.,  87.,  64.],
        [ 87., 135.,  57.],
        [103.,  43.,  36.],
        [ 68.,  97.,  70.]])

# Dataset and DataLoader
- for large dataset, inorder to reduce the computation time, we split ourt dataset into batches to make computations faster
- it also helps if our RAM is limited

In [54]:
from torch.utils.data import TensorDataset

In [55]:
# define dataset
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [56]:
from torch.utils.data import DataLoader

In [57]:
# define dataloader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

In [58]:
train_dl

- we can use for loop to get each batch in the dataloader
- if shuffle is set to true, the dataset will be shuffled before creating the batches
- shuffling is beneficial as, it introduces randomization, which in turn helps to train the model faster

In [59]:
for xb, yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[ 92.,  87.,  64.],
        [ 91.,  87.,  65.],
        [ 74.,  66.,  43.],
        [103.,  43.,  36.],
        [ 68.,  96.,  71.]])
tensor([[ 82., 100.],
        [ 80., 102.],
        [ 57.,  69.],
        [ 20.,  38.],
        [104., 118.]])


# nn.Linear
- Instead of initializing the weights & biases manually, we can define the model using the nn.Linear class from PyTorch, which does it automatically.

In [60]:
# define model
model = nn.Linear(3,2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.5300, -0.2559,  0.4611],
        [ 0.4940,  0.1440, -0.3699]], requires_grad=True)
Parameter containing:
tensor([ 0.2475, -0.1297], requires_grad=True)


- PyTorch models also have a helpful .parameters method, which returns a list containing all the weights and bias matrices present in the model. For our linear regression model, we have one weight matrix and one bias matrix.

In [61]:
# parameters
list(model.parameters())

[Parameter containing:
 tensor([[ 0.5300, -0.2559,  0.4611],
         [ 0.4940,  0.1440, -0.3699]], requires_grad=True),
 Parameter containing:
 tensor([ 0.2475, -0.1297], requires_grad=True)]

- we can use the model to generate predictions in the same way as before

In [62]:
preds = model(inputs)
preds

tensor([[41.6201, 29.6752],
        [55.4700, 33.8237],
        [38.8130, 40.6918],
        [60.3631, 42.7635],
        [44.5308, 21.8890],
        [42.4059, 30.0251],
        [56.1870, 33.3098],
        [39.8041, 40.8159],
        [59.5772, 42.4135],
        [44.4620, 21.0251],
        [42.3371, 29.1613],
        [56.2558, 34.1737],
        [38.0959, 41.2057],
        [60.4319, 43.6273],
        [43.7449, 21.5390]], grad_fn=<AddmmBackward0>)

In [63]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])

# Loss function
- instead of defining the loss function manually, we can use the in built loss function 'mse_loss'

In [64]:
import torch.nn.functional as F

In [65]:
# define loss function
loss_fn = F.mse_loss

In [66]:
# loss computation
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(3625.1155, grad_fn=<MseLossBackward0>)


# Optimizer
- Instead of manually manipulating the model's weights & biases using gradients, we can use the optimizer optim.SGD. SGD is short for "stochastic gradient descent". The term stochastic indicates that samples are selected in random batches instead of as a single group.

In [67]:
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

# Training the model

In [68]:
# utility function to train the model
def fit(num_epochs, model, loss_fn, opt, train_dl):
    
    # repeat for given number of epochs:
    for epoch in range(num_epochs):
        
        # train with batches of data
        for xb, yb in train_dl:
            
            # 1. generate predictions
            pred = model(xb)
            
            # 2. calculate loss
            loss = loss_fn(pred, yb)
            
            # 3. compute gradients
            loss.backward()
            
            # 4. performs SGD and update parameters(weights and biases) using gradients
            opt.step()
            
            # 5. reset gradients to zero
            opt.zero_grad()
        
        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

Some things to note above:

- We use the data loader defined earlier to get batches of data for every iteration.

- Instead of updating parameters (weights and biases) manually, we use opt.step to perform the update and opt.zero_grad to reset the gradients to zero.

- We've also added a log statement that prints the loss from the last batch of data for every 10th epoch to track training progress. loss.item returns the actual value stored in the loss tensor.

Let's train the model for 100 epochs.

In [69]:
fit(100, model, loss_fn, opt, train_dl)

Epoch [10/100], Loss: 913.7679
Epoch [20/100], Loss: 544.3702
Epoch [30/100], Loss: 350.9180
Epoch [40/100], Loss: 28.6401
Epoch [50/100], Loss: 225.2979
Epoch [60/100], Loss: 169.8360
Epoch [70/100], Loss: 135.3383
Epoch [80/100], Loss: 54.1606
Epoch [90/100], Loss: 70.8875
Epoch [100/100], Loss: 55.5929


In [70]:
# generate predictions
preds = model(inputs)
preds

tensor([[ 58.6370,  72.4299],
        [ 83.1841,  96.3122],
        [112.9302, 140.3107],
        [ 30.3316,  48.2102],
        [ 98.3552, 104.9360],
        [ 57.6766,  71.4584],
        [ 83.1408,  95.4901],
        [113.3513, 140.4716],
        [ 31.2920,  49.1818],
        [ 99.2724, 105.0855],
        [ 58.5938,  71.6079],
        [ 82.2236,  95.3406],
        [112.9734, 141.1328],
        [ 29.4143,  48.0608],
        [ 99.3157, 105.9076]], grad_fn=<AddmmBackward0>)

In [71]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])

# Predicting for new inputs

In [72]:
model(torch.tensor([[75.,63,44]])) # average temperature, rainfall humidity

tensor([[55.9606, 68.6876]], grad_fn=<AddmmBackward0>)

- the predicted yield of apples is 54.6 tons and 67.93 tons per hectare for the given parameters

# Creating feedforward neural networks

In [73]:
model2 = nn.Sequential(
    nn.Linear(3,4),
    nn.Sigmoid(),
    nn.Linear(4,2)
)

In [74]:
opt2 = torch.optim.SGD(model2.parameters(), lr = 1e-3)

In [75]:
fit(100, model2, F.mse_loss, opt2, train_dl)

Epoch [10/100], Loss: 7516.7920
Epoch [20/100], Loss: 4427.3765
Epoch [30/100], Loss: 4827.8232
Epoch [40/100], Loss: 4598.5093
Epoch [50/100], Loss: 3310.1570
Epoch [60/100], Loss: 2034.7351
Epoch [70/100], Loss: 2219.4907
Epoch [80/100], Loss: 3003.9380
Epoch [90/100], Loss: 1740.5010
Epoch [100/100], Loss: 1038.2936
