# Broadcasting

In [1]:
import numpy as np

In [10]:
A = np.array([[56, 0, 4.4, 68],
             [1.2, 104, 52, 8],
             [1.8, 135, 99, 0.9]])

In [11]:
sum = A.sum(axis=0)
print(sum)

[ 59.  239.  155.4  76.9]


In [13]:
percentage = 100*A/sum # this is where broadcasting occurs
                       # although we havent given the correct dimension of sum for matrix multiplication
                       # it automatically takes the correct dimension reshaping the matrix 
                       # but it is better to reshape the matrix yourself as you can have calculation
                       # errors when the matrix is square 

print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]
