In [1]:
import numpy as np

In [5]:
a = np.random.randn(5,)
# the above gives a rank 1 array
print(a)
print(a.shape)
print(np.dot(a,a.T))

[-1.47957457  1.03271714  1.58947677  0.43006437 -0.38364579]
(5,)
6.114221470605898


In [6]:
b = np.random.randn(5,1)
# the above gives a 5 by 1 matrix
print(b)
print(b.shape)
print(np.dot(b,b.T))

[[ 0.07085467]
 [ 0.66915249]
 [ 1.75722913]
 [ 0.19435708]
 [-0.03769707]]
(5, 1)
[[ 5.02038482e-03  4.74125812e-02  1.24507897e-01  1.37711077e-02
  -2.67101392e-03]
 [ 4.74125812e-02  4.47765049e-01  1.17585424e+00  1.30054525e-01
  -2.52250911e-02]
 [ 1.24507897e-01  1.17585424e+00  3.08785422e+00  3.41529927e-01
  -6.62423974e-02]
 [ 1.37711077e-02  1.30054525e-01  3.41529927e-01  3.77746756e-02
  -7.32669342e-03]
 [-2.67101392e-03 -2.52250911e-02 -6.62423974e-02 -7.32669342e-03
   1.42106942e-03]]


In [7]:
a = np.random.rand(4,3)
b = np.random.rand(1,3)
c = a*b
print(c)

[[0.27950658 0.0176215  0.59576742]
 [0.18804011 0.540526   0.51504886]
 [0.13019787 0.44967382 0.76774768]
 [0.52413924 0.10150986 0.12392788]]
